// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8H3sSP6fO6q8I0aihsyD7YHRkLYGokkM',
    appId: '1:605620668104:android:c6480840eb96c0852a87fd',
    messagingSenderId: '605620668104',
    projectId: 'food-td-e8ed0',
    databaseURL: 'https://food-td-e8ed0-default-rtdb.firebaseio.com',
    storageBucket: 'food-td-e8ed0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3_tg1WIb-Ul6vNwy94uHWgxde8KK_dec',
    appId: '1:605620668104:ios:36887c649caf5ae82a87fd',
    messagingSenderId: '605620668104',
    projectId: 'food-td-e8ed0',
    databaseURL: 'https://food-td-e8ed0-default-rtdb.firebaseio.com',
    storageBucket: 'food-td-e8ed0.firebasestorage.app',
    iosBundleId: 'com.tasolutions.restaurant-td',
  );

}